---
hero_image: images/codecraft.png
duration: 2
listed: true
copyedit: false
title: CodeCraft
description: Розробка та вдосконалення коду для 2D-версії Minecraft.
version: 3.1.0
last_tested: 2018-11-22
steps:
  - 
    title: З днем народження
  - 
    title: Граємо у гру
  - 
    title: 'Завдання: Побудуйте ваш світ'
  - 
    title: Налаштування вашої гри
  - 
    title: 'Завдання: Змініть розмір вашого світу'
  - 
    title: Створення нового дерев'яного ресурсу
  - 
    title: 'Завдання: Створення піску'
  - 
    title: Виготовлення дощок з дерева
  - 
    title: 'Завдання: Створення скла із піску'
  - 
    title: 'Завдання: Створіть більше ресурсів'
