---
hero_image: images / codecraft.png
theme: blauw
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-1, phys-comp-0, manufacture-0, community-0
title: CodeCraft
description: Ontwerp- en codeverbeteringen in een 2D-versie van Minecraft.
original_url: https://codeclubprojects.org/en-GB/python/codecraft
interests: games
technologies: Python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Inleiding
  - 
    title: Speel het spel
  - 
    title: 'Challenge: bouw je wereld'
  - 
    title: Je spel aanpassen
  - 
    title: 'Challenge: verander de grootte van je wereld'
  - 
    title: Maak een nieuwe bron voor hout
  - 
    title: 'Challenge: maak zand'
  - 
    title: Maak planken van hout
  - 
    title: 'Challenge: maak glas van zand'
  - 
    title: 'Challenge: meer bronnen maken'
