---
hero_image: images/codecraft.png
duration: 2
listed: true
copyedit: false
title: CodeCraft
description: Ontwerp- en codeverbeteringen in een 2D-versie van Minecraft.
version: 3.1.0
last_tested: 2018-11-22
steps:
  - 
    title: Inleiding
  - 
    title: Speel het spel
  - 
    title: 'Uitdaging: bouw je wereld'
  - 
    title: Je spel aanpassen
  - 
    title: 'Uitdaging: verander de grootte van je wereld'
  - 
    title: Maak een nieuwe bron voor hout
  - 
    title: 'Uitdaging: maak zand'
  - 
    title: Maak planken van hout
  - 
    title: 'Uitdaging: maak glas van zand'
  - 
    title: 'Uitdaging: meer bronnen maken'
