---
hero_image: images/codecraft.png
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-1, phys-comp-0, manufacture-0, community-0
title: CodeCraft
description: Design and code improvements to a 2D version of Minecraft.
original_url: https://codeclubprojects.org/en-GB/python/codecraft
interests: games
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introduction
  - 
    title: Playing the game
  - 
    title: 'Challenge: Build your world'
  - 
    title: Customising your game
  - 
    title: 'Challenge: Change your world size'
  - 
    title: Creating a new wood resource
  - 
    title: 'Challenge: Creating sand'
  - 
    title: Crafting planks from wood
  - 
    title: 'Challenge: Crafting glass from sand'
  - 
    title: 'Challenge: Create more resources'
