---
hero_image: images/codecraft.png
duration: 2
listed: true
copyedit: false
title: CodeCraft
description: Thiết kế và cải tiến mã cho phiên bản 2D của Minecraft.
version: 3.1.0
last_tested: 2018-11-22
steps:
  - 
    title: Giới thiệu
  - 
    title: Chơi trò chơi
  - 
    title: 'Thách thức: Xây dựng thế giới của bạn'
  - 
    title: Tùy chỉnh trò chơi của bạn
  - 
    title: 'Thách thức: Thay đổi kích thước thế giới của bạn'
  - 
    title: Tạo tài nguyên gỗ mới
  - 
    title: 'Thử thách: Tạo cát'
  - 
    title: Ván gỗ từ gỗ
  - 
    title: 'Thử thách: Chế tạo thủy tinh từ cát'
  - 
    title: 'Thách thức: Tạo thêm tài nguyên'
