---
hero_image: images / codecraft.png
duration: 2
listed: true
copyedit: false
title: CodeCraft
description: Design e melhorias de código para uma versão 2D do Minecraft.
version: 3.1.0
last_tested: 2018-11-22
steps:
  - 
    title: Introdução
  - 
    title: Jogando o jogo
  - 
    title: 'Desafio: Construa seu mundo'
  - 
    title: Personalizando seu jogo
  - 
    title: 'Desafio: mude seu tamanho do mundo'
  - 
    title: Criando um novo recurso de madeira
  - 
    title: 'Desafio: criando areia'
  - 
    title: Crafting pranchas de madeira
  - 
    title: 'Desafio: Crafting glass from sand'
  - 
    title: 'Desafio: criar mais recursos'
