---
hero_image: images / codecraft.png
theme: azul
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-1, phys-comp-0, manufacture-0, community-0
title: CodeCraft
description: Design e melhorias de código para uma versão 2D do Minecraft.
original_url: https://codeclubprojects.org/en-GB/python/codecraft
interests: games
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introdução
  - 
    title: Jogando o jogo
  - 
    title: 'Desafio: Construa seu mundo'
  - 
    title: Personalizando seu jogo
  - 
    title: 'Desafio: mude seu tamanho do mundo'
  - 
    title: Criando um novo recurso de madeira
  - 
    title: 'Desafio: criando areia'
  - 
    title: Crafting pranchas de madeira
  - 
    title: 'Desafio: Crafting glass from sand'
  - 
    title: 'Desafio: criar mais recursos'
