---
hero_image: images/codecraft.png
duration: 2
listed: true
copyedit: false
title: Codecraft
description: U ovom projektu dizajnirat ćeš i kodirati poboljšanja za 2D verziju igrice Minecraft.
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: CodeCraft
  - 
    title: Igranje igre
  - 
    title: 'Izazov: Izgradi svoj svijet'
  - 
    title: Prilagodba igre
  - 
    title: 'Izazov: Promijeni veličinu svog svijeta'
  - 
    title: Stvori novi resurs - drvo
  - 
    title: 'Izazov: Stvori pijesak'
  - 
    title: Izradi daske od drva
  - 
    title: 'Izazov: Izradi staklo od pijeska'
  - 
    title: 'Izazov: Stvori još elemenata'
