hero_image: images/codecraft.png
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Creación de códigos
description: Diseña y codifica mejoras de una versión en 2D de Minecraft.
original_url: https://codeclubprojects.org/en-GB/python/codecraft
interests: ''
technologies: python
site_areas: codeclub, python
steps:
- title: Introducción
- title: Jugar
- title: 'Reto: Crea tu propio mundo'
- title: Personalizar tu juego
- title: 'Reto: Cambia el tamaño de tu mundo'
- title: Creación de un nuevo recurso: madera
- title: 'Reto: Crear arena'
- title: Crear tablones de madera
- title: 'Reto: Crear cristal a partir de arena'
- title: 'Reto: Crea más recursos'

