---
hero_image: images/codecraft.png
duration: 2
listed: true
copyedit: false
title: CodeCraft
description: En este proyecto diseñarás y codificarás mejoras en una versión en 2D de Minecraft.
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introducción
  - 
    title: Jugar al juego
  - 
    title: 'Reto: Crea tu propio mundo'
  - 
    title: Personalizar tu juego
  - 
    title: 'Reto: Cambia el tamaño de tu mundo'
  - 
    title: 'Creación de un nuevo recurso: madera'
  - 
    title: 'Reto: Crear arena'
  - 
    title: 'Paso 4: Crear tablones de madera'
  - 
    title: 'Reto: Crear cristal a partir de arena'
  - 
    title: 'Reto: Crea más recursos'
