hero_image: images/codecraft.png
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: CodeCraft
description: Konzipiere und schreibe Code-Verbesserungen für eine 2D Version von Minecraft.
original_url: https://projects.raspberrypi.org/en/projects/codecraft
interests: ''
technologies: python
site_areas: codeclub, python
steps:
- title: Einführung
- title: Das Spiel spielen
- title: 'Aufgabe: Bau dir deine Welt'
- title: Du kannst dein Spiel persönlicher gestalten
- title: 'Aufgabe: Die Größe der Welt verändern'
- title: Eine neue Ressource aus Holz erstellen
- title: 'Aufgabe: Sand herstellen'
- title: Latten aus Holz herstellen
- title: 'Aufgabe: Glas aus Sand herstellen'
- title: 'Aufgabe: Weitere Ressourcen herstellen'

