---
hero_image: images/codecraft.png
duration: 2
listed: true
copyedit: false
title: CodeCraft
description: Načrtuj in kodiraj izboljšave za 2D verzijo Minecraft-a.
version: 3.1.0
last_tested: 2018-11-22
steps:
  - 
    title: Uvod
  - 
    title: Igranje igre
  - 
    title: 'Izziv: Zgradite svoj svet'
  - 
    title: Prilagodi svojo igro
  - 
    title: 'Izziv: Spremeni velikost svojega sveta'
  - 
    title: Ustvarjanje nove vrste lesa
  - 
    title: 'Izziv: Ustvarjanje peska'
  - 
    title: Izdelava desk iz lesa
  - 
    title: 'Izziv: Izdelava stekla iz peska'
  - 
    title: 'Izziv: Ustvarite več surovin'
