---
hero_image: 圖片/ codecraft.png
duration: 2
listed: true
copyedit: false
title: CodeCraft
description: 對Minecraft的2D版本進行設計和代碼改進。
version: 3.1.0
last_tested: 2018年11月22日
steps:
  - 
    title: 介紹
  - 
    title: 玩遊戲
  - 
    title: '挑戰：建立你的世界'
  - 
    title: 自定義您的遊戲
  - 
    title: '挑戰：改變你的世界大小'
  - 
    title: 創造新的木材資源
  - 
    title: '挑戰：創造沙子'
  - 
    title: 用木頭製作木板
  - 
    title: '挑戰：用沙子製作玻璃'
  - 
    title: '挑戰：創造更多資源'
