---
hero_image: images / codecraft.png
duration: 2
listed: true
copyedit: false
title: CodeCraft
description: Udoskonalenia projektu i kodu do wersji 2D Minecrafta.
version: 3.1.0
last_tested: 2018-11-22
steps:
  - 
    title: Wprowadzenie
  - 
    title: Grać w gre
  - 
    title: 'Wyzwanie: Zbuduj swój świat'
  - 
    title: Dostosowywanie swojej gry
  - 
    title: 'Wyzwanie: Zmień swój świat'
  - 
    title: Tworzenie nowego zasobu drewna
  - 
    title: 'Wyzwanie: tworzenie piasku'
  - 
    title: Wytwarzanie desek z drewna
  - 
    title: 'Wyzwanie: Wytwarzanie szkła z piasku'
  - 
    title: 'Wyzwanie: Utwórz więcej zasobów'
