---
hero_image: images/codecraft.png
duration: 2
listed: true
copyedit: false
title: CodeCraft
description: Poprawki projektu i kodu wersji 2D Minecraftu.
version: 3.1.0
last_tested: 22 listopada 2018
steps:
  - 
    title: Wprowadzenie
  - 
    title: Zasady gry
  - 
    title: 'Zadanie: tworzenie własnego świata'
  - 
    title: Ulepszanie gry
  - 
    title: 'Zadanie: zmiana rozmiarów świata'
  - 
    title: 'Tworzenie nowego zasobu: drewno'
  - 
    title: 'Zadanie: utworzyć piasek'
  - 
    title: Wytwarzanie desek z drewna
  - 
    title: 'Zadanie: wytwarzanie szkła z piasku'
  - 
    title: 'Zadanie: tworzenie nowych zasobów'
