hero_image: images/codecraft.png
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: CodeCraft
description: Dessiner et coder des améliorations dans une version 2D de Minecraft.
original_url: https://projects.raspberrypi.org/en/projects/codecraft
interests: ''
technologies: python
site_areas: codeclub, python
steps:
- title: Introduction
- title: Jouer le jeu
- title: 'Défi : Construire ton monde'
- title: Customisation de ton jeu
- title: 'Défi : Change la taille de ton monde'
- title: Créer une nouvelle ressource en bois
- title: 'Défi : Créer du sable'
- title: Façonner des planches de bois
- title: 'Défi : Façonner le verre du sable'
- title: 'Défi : Créer d'autres ressources'

