---
hero_image: images/codecraft.png
duration: 2
listed: true
copyedit: false
title: CodeCraft
description: Dessiner et coder des améliorations dans une version 2D de Minecraft.
version: 3.1.0
last_tested: 2018-11-22
steps:
  - 
    title: Introduction
  - 
    title: Jouer le jeu
  - 
    title: 'Défi : Construire ton monde'
  - 
    title: Customisation de ton jeu
  - 
    title: 'Défi : Change la taille de ton monde'
  - 
    title: Créer une nouvelle ressource en bois
  - 
    title: 'Défi : Créer du sable'
  - 
    title: Façonner des planches de bois
  - 
    title: 'Défi : Façonner le verre du sable'
  - 
    title: 'Défi : Créer d''autres ressources'
