---
hero_image: images/codecraft.png
duration: 2
listed: true
copyedit: false
title: CodeCraft
description: Dessiner et coder des améliorations dans une version 2D de Minecraft.
version: 3.1.0
last_tested: 2018-11-22
steps:
  - 
    title: Introduction
  - 
    title: Jouer au jeu
  - 
    title: 'Challenge : Construit ton monde'
  - 
    title: Personnalise ton jeu
  - 
    title: 'Challenge: Change la taille de ton monde'
  - 
    title: 'Crée une nouvelle ressource: le bois'
  - 
    title: 'Challenge: Crée du sable'
  - 
    title: Fabriquer des planches à partir du bois
  - 
    title: 'Challenge: Fabrique du verre à partir du sable'
  - 
    title: 'Challenge: Crée plus de ressources'
