hero_image: images/codecraft.png
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: CodeCraft
description: Miglioramenti al design e al codice di una versione 2D di Minecraft.
original_url: https://projects.raspberrypi.org/en/projects/codecraft
interests: ''
technologies: python
site_areas: codeclub, python
steps:
- title: Introduzione
- title: Il gioco
- title: 'Sfida: Costruisci il tuo mondo'
- title: Personalizzazione del gioco
- title: 'Sfida: Cambia le dimensioni del tuo mondo'
- title: Creazione di una nuova risorsa di legno
- title: 'Sfida: Crea la sabbia'
- title: Fabbricare tavole di legno
- title: 'Sfida: Fabbricare il vetro con la sabbia'
- title: 'Sfida: Crea altre risorse'

